// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.ArrayList;
import java.util.List;

public class Board {
	private List<Tile> tiles = new ArrayList<>();
	private List<Node> nodes = new ArrayList<>();
	private List<Road> roads = new ArrayList<>();

	public void setupDefaultMap() {
	}

	public void produceResources(int roll) {
	}

	public boolean canPlaceRoad(Player p, Node a, Node b) {
		return false;
	}

	public boolean placeRoad(Player p, Node a, Node b) {
		return false;
	}

	public boolean canPlaceSettlement(Player p, Node at) {
		return false;
	}

	public boolean placeSettlement(Player p, Node at) {
		return false;
	}

	public boolean canUpgradeToCity(Player p, Node at) {
		return false;
	}

	public boolean upgradeToCity(Player p, Node at) {
		return false;
	}
}
