// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private Tile[] tile;
	/**
	 * 
	 */
	private Node[] node;
	/**
	 * 
	 */
	private Road[] road;

	/**
	 * 
	 */
	public void setupDefaultMap() {
	}

	/**
	 * 
	 * @param roll 
	 */
	public void produceResources(int roll) {
	}

	/**
	 * 
	 * @param p 
	 * @param a 
	 * @param b 
	 * @return 
	 */
	public boolean canPlaceRoad(Player p, Node a, Node b) {
	}

	/**
	 * 
	 * @param p 
	 * @param a 
	 * @param b 
	 * @return 
	 */
	public boolean placeRoad(Player p, Node a, Node b) {
	}

	/**
	 * 
	 * @param p 
	 * @param at 
	 * @return 
	 */
	public boolean canPlaceSettlement(Player p, Node at) {
	}

	/**
	 * 
	 * @param p 
	 * @param at 
	 * @return 
	 */
	public boolean placeSettlement(Player p, Node at) {
	}

	/**
	 * 
	 * @param p 
	 * @param at 
	 * @return 
	 */
	public boolean canUpgradeToCity(Player p, Node at) {
	}

	/**
	 * 
	 * @param p 
	 * @param at 
	 * @return 
	 */
	public boolean upgradeToCity(Player p, Node at) {
	}
}
