// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Building {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Node Location;

	/**
	 * 
	 * @return 
	 */
	public int victoryPoints() {
	}
}
