// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public class Building {
	private Player owner;
	private Node location;

	public int victoryPoints() {
		return 0;
	}
}
