// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.Objects;

public abstract class Building {
    protected final Player owner;
    protected final Node location;

    protected Building(Player owner, Node location) {
        this.owner = Objects.requireNonNull(owner, "owner");
        this.location = Objects.requireNonNull(location, "location");
    }

    public Player getOwner() {
        return owner;
    }

    public Node getLocation() {
        return location;
    }

    public int victoryPoints(){
        return 1;
    };
}
