// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public final class City extends Building {
	public City(Player owner, Node location) {
		super(owner, location);
	}

}
