// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public class Cost {
	private int brick;
	private int lumber;
	private int wool;
	private int grain;
	private int ore;
	private int desert;

	public Cost road() {
		return null;
	}

	public Cost settlement() {
		return null;
	}

	public Cost city() {
		return null;
	}
}
