// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Cost {
	/**
	 * 
	 */
	private int brick;
	/**
	 * 
	 */
	private int lumber;
	/**
	 * 
	 */
	private int wool;
	/**
	 * 
	 */
	private int grain;
	/**
	 * 
	 */
	private int ore;
	/**
	 * 
	 */
	private int desert;

	/**
	 * 
	 * @return 
	 */
	public Cost road() {
	}

	/**
	 * 
	 * @return 
	 */
	public Cost settlement() {
	}

	/**
	 * 
	 * @return 
	 */
	public Cost city() {
	}
}
