// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

/**
 * Exports the current game state to a JSON file for the visualizer.
 * Output format matches the visualizer spec:
 * { "roads": [...], "buildings": [...] }
 */
public class GameStateExporter {
    private final String filePath;

    private static final String[] PLAYER_COLORS = {"RED", "BLUE", "WHITE", "ORANGE"};

    public GameStateExporter(String filePath) {
        this.filePath = filePath;
    }

    public static String playerColor(int playerId) {
        return PLAYER_COLORS[(playerId - 1) % PLAYER_COLORS.length];
    }

    public void export(Game game) {
        Board board = game.getBoard();
        StringBuilder sb = new StringBuilder();

        sb.append("{\n");

        // Roads
        sb.append("  \"roads\": [\n");
        List<Road> roads = board.getRoads();
        for (int i = 0; i < roads.size(); i++) {
            Road r = roads.get(i);
            sb.append("    { \"a\": ").append(r.getA().getNodeId())
              .append(", \"b\": ").append(r.getB().getNodeId())
              .append(", \"owner\": \"").append(playerColor(r.getOwner().getId())).append("\"")
              .append(" }");
            if (i < roads.size() - 1) sb.append(",");
            sb.append("\n");
        }
        sb.append("  ],\n");

        // Buildings
        sb.append("  \"buildings\": [\n");
        List<Node> nodes = board.getNodes();
        boolean first = true;
        for (Node n : nodes) {
            if (!n.isOccupied()) continue;
            Building b = n.getOccupant();
            String type = (b instanceof City) ? "CITY" : "SETTLEMENT";
            if (!first) sb.append(",\n");
            sb.append("    { \"node\": ").append(n.getNodeId())
              .append(", \"owner\": \"").append(playerColor(b.getOwner().getId())).append("\"")
              .append(", \"type\": \"").append(type).append("\"")
              .append(" }");
            first = false;
        }
        if (!first) sb.append("\n");
        sb.append("  ]\n");

        sb.append("}\n");

        try (FileWriter fw = new FileWriter(filePath)) {
            fw.write(sb.toString());
        } catch (IOException e) {
            System.err.println("Failed to export game state: " + e.getMessage());
        }
    }
}
