// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	private int round;
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	public Player[] players;

	/**
	 * 
	 * @return 
	 */
	public int getRound() {
	}

	/**
	 * 
	 */
	public void playRound() {
	}

	/**
	 * 
	 */
	public void run() {
	}

	/**
	 * 
	 * @return 
	 */
	public Player getWinner() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isFinished() {
	}
}
