// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.ArrayList;
import java.util.List;

public class Game {
	private int round;
	private int maxRounds;
	private Board board;
	private List<Player> players = new ArrayList<>();

	public int getRound() {
		return 0;
	}

	public void playRound() {
	}

	public void run() {
	}

	public Player getWinner() {
		return null;
	}

	public boolean isFinished() {
		return false;
	}
}
