// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public final class Node {
    private final int nodeId;
    private Building occupant; // null if empty

    public Node(int nodeId) {
        this.nodeId = nodeId;
    }

    public int getNodeId() {
        return nodeId;
    }

    public boolean isOccupied() {
        return occupant != null;
    }

    public Building getOccupant() {
        return occupant;
    }

    public void place(Building b) {
        if (b == null) throw new IllegalArgumentException("building cannot be null");
        this.occupant = b;
    }

    public void clear() {
        this.occupant = null;
    }
}