// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public class Node {
	private int nodeID;
	private Building occupant;

	public boolean isOccupied() {
		return false;
	}

	public void place(Building b) {
	}

	public void clean() {
	}
}
