// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int nodeID;
	/**
	 * 
	 */
	private Building occupant;

	/**
	 * 
	 */
	public Building ;
	/**
	 * 
	 * @return 
	 */
	public boolean isOccupied() {
	}

	/**
	 * 
	 * @param b 
	 */
	public void place(Building b) {
	}

	/**
	 * 
	 */
	public void clean() {
	}
}
