// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private int victoryPoints;
	/**
	 * 
	 */
	private ResourceCard hand;
	/**
	 * 
	 */
	private Road roads;
	/**
	 * 
	 */
	private Settlement settlements;
	/**
	 * 
	 */
	private City cities;

	/**
	 * 
	 * @param game 
	 */
	public void takeTurn(Game game) {
	}

	/**
	 * 
	 * @param type 
	 * @param count 
	 */
	public void addResources(ResourceType type, int count) {
	}

	/**
	 * 
	 * @param cost 
	 * @return 
	 */
	public boolean hasResources(Cost cost) {
	}

	/**
	 * 
	 * @param cost 
	 */
	public void Pay(Cost cost) {
	}

	/**
	 * 
	 */
	public void updateVictoryPoints() {
	}
}
