// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.ArrayList;
import java.util.List;

public class Player {
	private int id;
	private int victoryPoints;
	private List<ResourceCard> hand = new ArrayList<>();
	private List<Road> roads = new ArrayList<>();
	private List<Settlement> settlements = new ArrayList<>();
	private List<City> cities = new ArrayList<>();

	public void takeTurn(Game game) {
	}

	public void addResources(ResourceType type, int count) {
	}

	public boolean hasResources(Cost cost) {
		return false;
	}

	public void Pay(Cost cost) {
	}

	public void updateVictoryPoints() {
	}
}
