// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

import java.util.Objects;

public final class ResourceCard {
	private final ResourceType type;

	public ResourceCard(ResourceType type) {
		this.type = Objects.requireNonNull(type, "type");
	}

	public ResourceType type() {
		return type;
	}
}