// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public class ResourceCard {
	public ResourceType type;

	public ResourceType type() {
		return null;
	}
}
