// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public class Road {
	private Player owner;
	private Node a;
	private Node b;

	public boolean connects(Node n) {
		return false;
	}
}
