// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Road {
	/**
	 * 
	 */
	private Player owner;
	/**
	 * 
	 */
	private Node a;
	/**
	 * 
	 */
	private Node b;

	/**
	 * 
	 */
	public Node ;
				/**
				 * 
				 */
				public Node ;
	/**
	 * 
	 * @param n 
	 * @return 
	 */
	public boolean connects(Node n) {
	}
}
