// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Settlement extends Building {
	/**
	 * 
	 * @return 
	 */
	public int victoryPoints() {
	}
}
