// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public final class Settlement extends Building {
	public Settlement(Player owner, Node location) {
		super(owner, location);
	}
}
