// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public class Settlement extends Building {
	public int victoryPoints() {
		return 0;
	}
}
