// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

public class Tile {
	private int tileID;
	private ResourceType resourceType;
	private int numberToken;

	public boolean producesOn(int roll) {
		return false;
	}

	public boolean isDesert() {
		return false;
	}
}
