// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Catan;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int tileID;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int numberToken;

	/**
	 * 
	 */
	public ResourceType ;
	/**
	 * 
	 * @param roll 
	 * @return 
	 */
	public boolean producesOn(int roll) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean isDesert() {
	}
}
